version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/app
    # 포트를 nginx에만 노출하도록 설정
    expose:
      - 8000
    env_file:
      - ./env_files/.env
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:1.17.10
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  mongodb_data: