version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./env_files/.env
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: